# local.yml

db:
  type: 'mysql'
  replication:
    master:
      host: localhost
      port: 3306
      username: root
      password: '1234'
      database: myboard
    slaves:
      - host: localhost
        port: 3306
        username: root
        password: '1234'
        database: myboard
      - host: localhost
        port: 3306
        username: root
        password: '1234'
        database: myboard
  canRetry: true
  selector: RR

auth:
  jwt:
    secret: "nest-test1234"
    signOptions:
      expiresIn: 3600  # 토큰 만료 시간 (초 단위)
